### ISSUE TITLE
Switch float to uint64

### ISSUE THREAD

**Issue by michaeljs1990** [michaeljs1990/collins-go-cli#50]
```
$ collins query --limit 100 -x disk_storage_human
panic: runtime error: index out of range [-9223372036854775808]

goroutine 1 [running]:
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.BytesToHumanSize(0x0, 0xc000240f66, 0x9)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/util.go:59 +0x211
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.fieldToAssetStruct.func16(0x7ffeefbff9ed, 0x14763c7)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/format.go:146 +0xd8
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.emptyOrValue(...)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/format.go:31
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.fieldToAssetStruct(0x7ffeefbff9ed, 0x12, 0x2b, 0xc0002403a2, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc0002403b3, ...)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/format.go:140 +0x13cb
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.renderTable(0x147168c, 0x1, 0xc000018600, 0xc00022a7e0, 0x8, 0xe, 0xc0005b0000, 0x1f, 0x21)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/format.go:172 +0x18b
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.formatAssets(0x1471f88, 0x5, 0x147168c, 0x1, 0x0, 0xc0004dcae0, 0x26, 0x0, 0xc00022a7e0, 0x8, ...)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/format.go:17 +0x1dc
cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands.queryRunCommand(0xc000001b00, 0xc000095800, 0xc000001b00)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/collins/commands/query.go:475 +0xb8f
cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli.HandleAction(0x13eb0e0, 0x148ea88, 0xc000001b00, 0x0, 0xc000012e40)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli/app.go:521 +0xc8
cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli.Command.Run(0x1471f47, 0x5, 0x0, 0x0, 0xc00005ae50, 0x1, 0x1, 0x147ab94, 0x1c, 0x0, ...)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli/command.go:167 +0x476
cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli.(*App).Run(0xc0000ce1c0, 0xc000012240, 0x6, 0x6, 0x0, 0x0)
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/vendor/github.com/urfave/cli/app.go:274 +0x6c2
main.main()
	/Users/michaelschuett/gocode/src/cgit.xrt0x.com/xrt0x/collins-go-cli/cmd/collins/main.go:55 +0x2781
```

**Comment by michaeljs1990** [comment]
This issue is fixed although the specific index out of range error showing the lowest number for a float64 doesn't make total sense.... We have a check in place now so we won't try and access an index position that doesn't exist.
